server.port=8080
spring.output.ansi.enabled=ALWAYS

logging.level.com.damu=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

app.security.jwt.issuer=${IAM_JWT_ISSUER:http://localhost:8083}
app.security.jwt.audience=${IAM_JWT_AUDIENCE:shop-api}
app.security.jwt.public-key=${IAM_JWT_PUBLIC_KEY:MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCzhDk+9gYWkTzQzJ6WsgRrhtLSiOHtKFrUdOEywUZphZicbZ/ZJP/rYs9Hz6GC7lcwfH+Kdd8za4Bp5FsOM1WNREv0xxQxVgFIvs+ixpT91GczDwqapJOLgaWLJ1z3vSrgGvc5yvCFMH71yKEZ2pf5inWQUSnDMrPWGqpnkW15wIDAQAB}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/productdb
spring.datasource.username=damu
spring.datasource.password=password123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.application.name=PRODUCT-SERVICE
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:9296}
