server.port=8080
spring.output.ansi.enabled=ALWAYS

logging.level.com.damu=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

app.security.jwt.issuer=${IAM_JWT_ISSUER:http://localhost:8083}
app.security.jwt.audience=${IAM_JWT_AUDIENCE:shop-api}
app.security.jwt.public-key=${IAM_JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsQLVFs53lYpXcfuoifwwOl1MQhKqWsF/YwhgN+7Mtm2SUrOjdKqE/Sq+bjdQTNS2E65pQ+/qFKITkMJdPvh8it5W/IYW000mNL1WESfMLl0Jxuc3pGfmU25Hr7dF0IeLqeciZViq5STIf/2t0Y1ErgSVT5+4xxltTHTo1X6T5jlpU3DpH9TDspf1zc/yPmmSXyu1dUmpuV+PObdiIVOHp72C9YJIV6vVn188yjN88j8Bma62RQ2xoln88xm//uDvfruivXEn2+knVEvMtm2YKTebwMc5Y25Y1uqgImfvzQMTja1vHVz8yfqO+S3dhocizelJzHsglGLFbnCsXeIL5QIDAQAB}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/productdb
spring.datasource.username=damu
spring.datasource.password=password123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.application.name=PRODUCT-SERVICE
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:9296}
