
server:
  port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-},%X{spanId:-}] [correlationId=%X{correlationId:-}] [${spring.application.name:-application}] %logger{36} - %msg%n"
  level:
    com.damu: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: damu
    password: password123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-15585796.okta.com/oauth2/default
