server.port=8081

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-},%X{spanId:-}] [correlationId=%X{correlationId:-}] [${spring.application.name:-application}] %logger{36} - %msg%n
logging.level.com.damu=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN

app.security.jwt.issuer=${IAM_JWT_ISSUER:http://localhost:8083}
app.security.jwt.audience=${IAM_JWT_AUDIENCE:shop-api}
app.security.jwt.secret=${IAM_JWT_SECRET:2MYI7CSmDvVcNU3IdTyE/rpzUGNkR2cPeabl5+/nuHdukRpVTbiKlwoWRfiZMbKf216DVmqzmnjLyAhgFOstUA==}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
spring.datasource.username=damu
spring.datasource.password=password123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.application.name=PAYMENT-SERVICE
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:9296}
