server.port=9296

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-},%X{spanId:-}] [correlationId=%X{correlationId:-}] [${spring.application.name:-application}] %logger{36} - %msg%n
logging.level.com.damu=INFO
logging.level.org.springframework.cloud.config=INFO

spring.application.name=CONFIG-SERVER
spring.cloud.config.server.git.uri=https://github.com/shabbirdwd53/spring-app-config
spring.cloud.config.server.git.clone-on-start=true

eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
