server.port=8761
spring.output.ansi.enabled=ALWAYS

logging.level.com.damu=INFO
logging.level.com.netflix.eureka=INFO

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
