server.port=9090
spring.output.ansi.enabled=ALWAYS

logging.level.com.damu=INFO
logging.level.org.springframework.cloud.gateway=INFO

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
management.zipkin.tracing.export.enabled=${ZIPKIN_ENABLED:false}

app.security.jwt.issuer=${IAM_JWT_ISSUER:http://localhost:8083}
app.security.jwt.audience=${IAM_JWT_AUDIENCE:shop-api}
app.security.jwt.public-key=${IAM_JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsQLVFs53lYpXcfuoifwwOl1MQhKqWsF/YwhgN+7Mtm2SUrOjdKqE/Sq+bjdQTNS2E65pQ+/qFKITkMJdPvh8it5W/IYW000mNL1WESfMLl0Jxuc3pGfmU25Hr7dF0IeLqeciZViq5STIf/2t0Y1ErgSVT5+4xxltTHTo1X6T5jlpU3DpH9TDspf1zc/yPmmSXyu1dUmpuV+PObdiIVOHp72C9YJIV6vVn188yjN88j8Bma62RQ2xoln88xm//uDvfruivXEn2+knVEvMtm2YKTebwMc5Y25Y1uqgImfvzQMTja1vHVz8yfqO+S3dhocizelJzHsglGLFbnCsXeIL5QIDAQAB}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=API Gateway
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[1].name=Order Service
springdoc.swagger-ui.urls[1].url=/order/v3/api-docs
springdoc.swagger-ui.urls[2].name=Payment Service
springdoc.swagger-ui.urls[2].url=/payment/v3/api-docs
springdoc.swagger-ui.urls[3].name=Product Service
springdoc.swagger-ui.urls[3].url=/product/v3/api-docs
springdoc.swagger-ui.urls[4].name=User Service
springdoc.swagger-ui.urls[4].url=/user/v3/api-docs
springdoc.swagger-ui.urls[5].name=Notification Service
springdoc.swagger-ui.urls[5].url=/notification/v3/api-docs

spring.application.name=API-GATEWAY
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:9296}

spring.cloud.gateway.server.webmvc.routes[0].id=USER-SERVICE-AUTH
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=ORDER-SERVICE-OPENAPI
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/order/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=PAYMENT-SERVICE-OPENAPI
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/payment/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[3].id=PRODUCT-SERVICE-OPENAPI
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/product/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[4].id=USER-SERVICE-OPENAPI
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/user/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[5].id=NOTIFICATION-SERVICE-OPENAPI
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/notification/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[6].id=ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/order/**
spring.cloud.gateway.server.webmvc.routes[6].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[6].filters[0].args.name=ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].filters[0].args.fallbackUri=forward:/orderServiceFallBack

spring.cloud.gateway.server.webmvc.routes[7].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/payment/**
spring.cloud.gateway.server.webmvc.routes[7].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[7].filters[0].args.name=PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].filters[0].args.fallbackUri=forward:/paymentServiceFallBack

spring.cloud.gateway.server.webmvc.routes[8].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/product/**
spring.cloud.gateway.server.webmvc.routes[8].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[8].filters[0].args.name=PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].filters[0].args.fallbackUri=forward:/productServiceFallBack

spring.cloud.gateway.server.webmvc.routes[9].id=USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webmvc.routes[9].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[9].filters[0].args.name=USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[9].filters[0].args.fallbackUri=forward:/userServiceFallBack

spring.cloud.gateway.server.webmvc.routes[10].id=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/notification/**
spring.cloud.gateway.server.webmvc.routes[10].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[10].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webmvc.routes[10].filters[1].args.name=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[10].filters[1].args.fallbackUri=forward:/notificationServiceFallBack

resilience4j.timelimiter.instances.ORDER-SERVICE.timeout-duration=5s
resilience4j.timelimiter.instances.PAYMENT-SERVICE.timeout-duration=5s
resilience4j.timelimiter.instances.PRODUCT-SERVICE.timeout-duration=5s
resilience4j.timelimiter.instances.USER-SERVICE.timeout-duration=5s
resilience4j.timelimiter.instances.NOTIFICATION-SERVICE.timeout-duration=8s
